plugin:
    name: 'paulvonzimmerman.patreon::lang.plugin.name'
    description: 'paulvonzimmerman.patreon::lang.plugin.description'
    author: PaulVonZimmerman
    icon: oc-icon-adjust
    homepage: ''
navigation:
    Patreon:
        label: Patreon
        url: paulvonzimmerman/patreon/register
        icon: icon-money
        permissions:
            - paulvonzimmerman.patreon.manage_register
permissions:
    paulvonzimmerman.patreon.manage_register:
        tab: 'paulvonzimmerman.patreon::lang.plugin.name'
        label: Manage
