plugin:
    name: 'paul.patreon::lang.plugin.name'
    description: 'paul.patreon::lang.plugin.description'
    author: paul
    icon: oc-icon-adjust
    homepage: ''
navigation:
    Patreon:
        label: Patreon
        url: paul/patreon/register
        icon: icon-money
        permissions:
            - paul.patreon.manage_register
permissions:
    paul.patreon.manage_register:
        tab: 'paul.patreon::lang.plugin.name'
        label: Manage
