name: Register
modelClass: Paul\Patreon\Models\Register
form: $/paul/patreon/models/register/fields.yaml
defaultRedirect: paul/patreon/register
create:
    redirect: 'paul/patreon/register/update/:id'
    redirectClose: paul/patreon/register
update:
    redirect: paul/patreon/register
    redirectClose: paul/patreon/register
